/**
 * Copies the 2D sprite pack from assets/renderMii_sprites into
 * apps/web/public/sprites so the web app can load it at runtime.
 *
 * The Nintendo sprite sheets are never committed: run this after cloning.
 *
 * Usage: pnpm sync-assets
 */
import { cpSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..', '..')
const source = join(repoRoot, 'assets', 'renderMii_sprites')
const target = join(repoRoot, 'apps', 'web', 'public', 'sprites')

const REQUIRED = [
  'mii_heads.png',
  'mii_hairs1.png',
  'mii_hairs2.png',
  'mii_eyebrows.png',
  'mii_eyes1.png',
  'mii_eyes2.png',
  'mii_eyes3.png',
  'mii_noses.png',
  'mii_lips.png',
  'mii_glasses.png',
  'mii_beards.png',
  'mii_mustache.png',
  'mii_features.png',
  'mii_mole.png',
]

function main() {
  const missing = REQUIRED.filter((file) => {
    try {
      return !statSync(join(source, file)).isFile()
    } catch {
      return true
    }
  })
  if (missing.length > 0) {
    throw new Error(
      `Sprite sheets missing in ${source}: ${missing.join(', ')}\nDownload renderMii_sprites.zip and extract it under assets/ (see docs/MII_FORMAT_RESEARCH.md section 13).`,
    )
  }

  mkdirSync(target, { recursive: true })
  for (const file of REQUIRED) {
    cpSync(join(source, file), join(target, file))
  }

  const total = REQUIRED.reduce((sum, file) => sum + statSync(join(target, file)).size, 0)
  writeFileSync(
    join(target, 'README.txt'),
    `Generated by tools/sync-assets. Do not edit or commit: Nintendo sprite assets.\nFiles: ${REQUIRED.length} (${readdirSync(target).length - 1} sheets), ${(total / 1024).toFixed(0)} KiB.\n`,
  )
  console.log(`sync-assets: ${REQUIRED.length} sheets (${(total / 1024).toFixed(0)} KiB) -> apps/web/public/sprites`)
}

main()
